# As of May 2, 2020; Virtualbox is available in backports, but is an old version.
# The following will add the official Virtualbox repo

#- name: software | virtualbox | install apt key (debian)
#  tags: virtualbox,repositories,virtualbox
#  apt_key:
#    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#    state: present
#  when:
#    - ansible_distribution == "Debian"
#    - virtualbox is defined
#    - virtualbox == true
#
#- name: software | virtualbox | install repository (debian)
#  tags: virtualbox,repositories,virtualbox
#  apt_repository:
#    repo: deb https://download.virtualbox.org/virtualbox/debian buster contrib
#    state: present
#    filename: virtualbox
#  register: virtualbox_repo_debian
#  when:
#    - ansible_distribution == "Debian"
#    - virtualbox is defined
#    - virtualbox == true
#
#- name: software | virtualbox | install package
#  tags: virtualbox
#  package:
#    name: "{{ virtualbox_package }}"
#  when:
#    - virtualbox is defined
#    - virtualbox == true


      
    ### distributive repo version

- name: system setup | virtualization packages | install virtualbox
  tags: dev,virtualization,packages,virtualbox
  package:
    name:
      - virtualbox
        #- virtualbox-ext-pack #TODO ERROR: "User did not accept the license."
        #- linux-headers-$(uname -r) #TODO replace bash parameter expansion
      - virtualbox-dkms
      - virtualbox-guest-additions-iso
      - virtualbox-guest-utils-hwe
      - virtualbox-guest-x11-hwe
    state: latest
  #notify:
  #  - add_user_ub_to_kvm_group
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")

- name: system setup | virtualization packages | install virtualbox
  tags: dev,virtualization,packages,virtualbox
  package:
    name:
      - virtualbox
        #- virtualbox-ext-pack #TODO ERROR: "User did not accept the license."
        #- linux-headers-$(uname -r) #TODO replace bash parameter expansion
      - virtualbox-host-dkms
      #- linux65-virtualbox-host-modules
      - virtualbox-guest-iso
    state: latest
  #notify:
  #  - add_user_ub_to_kvm_group
  when: ansible_os_family == "Archlinux"

