- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - fdupes
      - jdupes
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - cifs-utils
      - "{{ nfs_client_package }}"
      - nmap
      - ranger
      - rclone
      - "{{ rename_package }}"
      - rclone
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - unison
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
