#- name: test
#  tags: test
#  ansible.builtin.lineinfile:
#    path: /test
#    #line: 'Acquire::http::proxy "http://192.168.122.1:8000";'
#    line: 'A test split'
#    create: yes
#    owner: root
#    group: root
#    mode: '0644'

- name: system setup | virtualization packages | install qemu
  tags: dev,virtualization,packages,qemu
  package:
    name:
      - qemu-kvm
      - bridge-utils
      - libvirt-daemon-system
      - libvirt-daemon
      - libvirt-clients
    state: latest
  notify:
    - add_user_ub_to_kvm_group
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")

